Modificato glossario e reso l'indice in ordine alfabetico
4ourSquared/LumosMinima pull request #99
Opened 2023-08-15 13:41 UTC by nicolasalberti00

Attendo revisione

2023-08-15 16:18 UTC, matnut2 requested changes
Non va bene: nell'intestazione, anche nelle pagine di contenuto appare la dicitura "indice"

2023-08-15 16:25 UTC, nicolasalberti00 commented
Più tardi sistemo allora

2023-08-15 16:26 UTC, matnut2 commented
Scusa FRA

2023-08-16 06:47 UTC, nicolasalberti00 commented
Ho effettuato la modifica, controlla che sia tutto apposto, anche se ora mi pare di si

2023-08-16 12:14 UTC, matnut2 approved these changes
Croccante

2023-08-16 12:14 UTC, merged